version: '3'

services:
  fastapi:
    build: .
    image: custom-fastapi:latest
    depends_on:
      - db
    volumes:
      - .:/app:rw
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@db:5432/dockert
    ports:
      - "8002:8002"
    
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert

volumes:
  postgres_data:
